version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: soroush
      POSTGRES_PASSWORD: @Soroush1381
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: banking-system
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/banking
      SPRING_DATASOURCE_USERNAME: soroush
      SPRING_DATASOURCE_PASSWORD: @Soroush1381

volumes:
  postgres-data:
