version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: soroush
      POSTGRES_PASSWORD: Soroush1381
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

  app:
    build: .
    container_name: banking-system
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/banking
      SPRING_DATASOURCE_USERNAME: soroush
      SPRING_DATASOURCE_PASSWORD: Soroush1381
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  postgres-data:
